[package]
name = "webview_rust"
version = "0.1.0"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@sfosc.org>", "Tensor Programming <tensordeveloper@gmail.com>", "zserge"]
readme = "README.md"
license = "MIT / Apache 2"
repository = "https://github.com/tauri-apps/webview_rust"
description = "Official Webview-org Rust bindings, a tiny cross-platform library to render web-based GUIs for desktop applications"
keywords = ["web", "gui", "desktop", "webkit"]
categories = ["gui", "api-bindings"]
build = "build.rs"
edition = "2018"

[lib]
name = "webview_rust_sys"
path = "src/lib.rs"

[[example]]
name = "sample"
path = "examples/sample.rs"

[target.'cfg(all(target_family = "unix", not(target_os = "macos")))'.dependencies]
javascriptcore-rs-sys = "0.2"
gtk-sys = "0.9"
glib-sys = "0.9"
gobject-sys = "0.9"
webkit2gtk-sys = { version = "0.10", features = ["v2_8"] }
gdk-sys = "0.9"
gio-sys = "0.9"
libc = "0.2"


[build-dependencies]
cc = "1"
pkg-config = "0.3"